// forge-app/front/src/components/Navbar.svelte
<script>
  import { LOGOUT_URL } from '../lib/api.js'
  import { me, businesses, currentBusinessId, shift, setCurrentBusiness } from '../lib/session.js'
  import { GLOBAL_ROLE_LABELS } from '../lib/roles.js'
  import Badge from './ui/Badge.svelte'
  import Button from './ui/Button.svelte'

  let user = $derived($me.user)
  let displayName = $derived(user.inGameName ?? user.username)
  let initials = $derived(displayName.slice(0, 2).toUpperCase())
</script>

<header class="flex min-h-16 items-center justify-between gap-3 border-b bg-background/75 px-4 backdrop-blur lg:px-8">
  <div class="flex items-center gap-3">
    <div class="hidden sm:block">
      <p class="text-sm text-muted-foreground">Forge RP</p>
      <h1 class="text-xl font-semibold">Tableau de bord</h1>
    </div>

    {#if $businesses.length === 0}
      <span class="text-xs text-muted-foreground">Aucun business</span>
    {:else}
      <select
        aria-label="Business courant"
        class="h-9 rounded-md border bg-input/30 px-3 text-sm"
        value={$currentBusinessId ?? ''}
        onchange={(e) => setCurrentBusiness(e.currentTarget.value)}
      >
        {#each $businesses as b}
          <option value={b.id}>{b.nom}</option>
        {/each}
      </select>
    {/if}

    {#if $shift?.open}
      <span class="inline-flex items-center gap-1.5 rounded-full border border-emerald-500/40 bg-emerald-500/15 px-2.5 py-0.5 text-xs font-medium text-emerald-400">
        <span class="size-1.5 animate-pulse rounded-full bg-emerald-400"></span>
        Service en cours
      </span>
    {/if}
  </div>

  <div class="flex items-center gap-3">
    <Badge variant="outline">{GLOBAL_ROLE_LABELS[user.globalRole]}</Badge>
    <div class="flex size-9 items-center justify-center overflow-hidden rounded-full bg-muted text-sm font-medium">
      {#if user.avatar}
        <img src={user.avatar} alt={user.username} class="size-full object-cover" />
      {:else}
        {initials}
      {/if}
    </div>
    <div class="hidden text-right sm:block">
      <p class="text-sm font-medium">{displayName}</p>
      <p class="text-xs text-muted-foreground">@{user.username}</p>
    </div>
    <Button variant="outline" size="sm" onclick={() => (window.location.href = LOGOUT_URL)}>
      Déconnexion
    </Button>
  </div>
</header>

// components/layout/navbar.tsx
import { signOut } from "@/auth"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import { RoleBadge } from "@/components/layout/role-badge"

export function Navbar({
  user,
}: {
  user: {
    name?: string | null
    inGameName?: string | null
    discordUsername?: string | null
    image?: string | null
    role: "ADMIN" | "GERANT" | "FORGERON"
  }
}) {
  const displayName = user.inGameName ?? user.name ?? "Profil"
  const initials = displayName.slice(0, 2).toUpperCase()

  return (
    <header className="flex min-h-16 items-center justify-between border-b bg-background/75 px-4 backdrop-blur lg:px-8">
      <div>
        <p className="text-sm text-muted-foreground">Forge RP</p>
        <h1 className="text-xl font-semibold">Atelier & commandes</h1>
      </div>

      <div className="flex items-center gap-3">
        <RoleBadge role={user.role} />
        <Avatar className="size-9">
          <AvatarImage src={user.image ?? undefined} alt={user.name ?? "Avatar Discord"} />
          <AvatarFallback>{initials}</AvatarFallback>
        </Avatar>
        <div className="hidden text-right sm:block">
          <p className="text-sm font-medium">{displayName}</p>
          <p className="text-xs text-muted-foreground">Session active</p>
        </div>
        <form
          action={async () => {
            "use server"
            await signOut({ redirectTo: "/" })
          }}
        >
          <Button type="submit" variant="outline" size="sm">
            Déconnexion
          </Button>
        </form>
      </div>
    </header>
  )
}
