// forge-app/front/src/components/Navbar.svelte
<script>
  import { LOGOUT_URL } from '../lib/api.js'
  import { me, businesses, currentBusinessId, shift, setCurrentBusiness } from '../lib/session.js'
  import { GLOBAL_ROLE_LABELS } from '../lib/roles.js'
  import Badge from './ui/Badge.svelte'
  import Button from './ui/Button.svelte'

  let user = $derived($me.user)
  let displayName = $derived(user.inGameName ?? user.username)
  let initials = $derived(displayName.slice(0, 2).toUpperCase())
</script>

<header class="flex min-h-16 items-center justify-between gap-3 border-b bg-background/75 px-4 backdrop-blur lg:px-8">
  <div class="flex items-center gap-3">
    <div class="hidden sm:block">
      <p class="text-sm text-muted-foreground">Forge RP</p>
      <h1 class="text-xl font-semibold">Tableau de bord</h1>
    </div>

    {#if $businesses.length === 0}
      <span class="text-xs text-muted-foreground">Aucun business</span>
    {:else}
      <select
        aria-label="Business courant"
        class="h-9 rounded-md border bg-input/30 px-3 text-sm"
        value={$currentBusinessId ?? ''}
        onchange={(e) => setCurrentBusiness(e.currentTarget.value)}
      >
        {#each $businesses as b}
          <option value={b.id}>{b.nom}</option>
        {/each}
      </select>
    {/if}

    {#if $shift?.open}
      <span class="inline-flex items-center gap-1.5 rounded-full border border-emerald-500/40 bg-emerald-500/15 px-2.5 py-0.5 text-xs font-medium text-emerald-400">
        <span class="size-1.5 animate-pulse rounded-full bg-emerald-400"></span>
        Service en cours
      </span>
    {/if}
  </div>

  <div class="flex items-center gap-3">
    <Badge variant="outline">{GLOBAL_ROLE_LABELS[user.globalRole]}</Badge>
    <div class="flex size-9 items-center justify-center overflow-hidden rounded-full bg-muted text-sm font-medium">
      {#if user.avatar}
        <img src={user.avatar} alt={user.username} class="size-full object-cover" />
      {:else}
        {initials}
      {/if}
    </div>
    <div class="hidden text-right sm:block">
      <p class="text-sm font-medium">{displayName}</p>
      <p class="text-xs text-muted-foreground">@{user.username}</p>
    </div>
    <Button variant="outline" size="sm" onclick={() => (window.location.href = LOGOUT_URL)}>
      Déconnexion
    </Button>
  </div>
</header>

// forge-app/front/components/layout/navbar.tsx
"use client"

import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { SelectField } from "@/components/ui/select-field"
import { LOGOUT_URL } from "@/lib/api"
import { useCurrentBusiness } from "@/lib/current-business"
import { GLOBAL_ROLE_LABELS, type Me } from "@/lib/roles"
import { useShift } from "@/lib/shift"

function ShiftIndicator() {
  const { shift } = useShift()
  if (!shift?.open) return null
  return (
    <span className="inline-flex items-center gap-1.5 rounded-full border border-emerald-500/40 bg-emerald-500/15 px-2.5 py-0.5 text-xs font-medium text-emerald-400">
      <span className="size-1.5 animate-pulse rounded-full bg-emerald-400" />
      Service en cours
    </span>
  )
}

function BusinessSelector() {
  const { businesses, currentId, setCurrentId } = useCurrentBusiness()

  if (businesses.length === 0) {
    return <span className="text-xs text-muted-foreground">Aucun business</span>
  }

  return (
    <SelectField
      ariaLabel="Business courant"
      value={currentId ?? ""}
      onChange={setCurrentId}
      options={businesses.map((b) => ({ value: b.id, label: b.nom }))}
    />
  )
}

export function Navbar({ me }: { me: Me }) {
  const user = me.user
  const displayName = user.inGameName ?? user.username
  const initials = displayName.slice(0, 2).toUpperCase()

  return (
    <header className="flex min-h-16 items-center justify-between gap-3 border-b bg-background/75 px-4 backdrop-blur lg:px-8">
      <div className="flex items-center gap-3">
        <div className="hidden sm:block">
          <p className="text-sm text-muted-foreground">Forge RP</p>
          <h1 className="text-xl font-semibold">Tableau de bord</h1>
        </div>
        <BusinessSelector />
        <ShiftIndicator />
      </div>

      <div className="flex items-center gap-3">
        <Badge variant="outline">{GLOBAL_ROLE_LABELS[user.globalRole]}</Badge>
        <Avatar className="size-9">
          <AvatarImage src={user.avatar ?? undefined} alt={user.username} />
          <AvatarFallback>{initials}</AvatarFallback>
        </Avatar>
        <div className="hidden text-right sm:block">
          <p className="text-sm font-medium">{displayName}</p>
          <p className="text-xs text-muted-foreground">@{user.username}</p>
        </div>
        <Button
          variant="outline"
          size="sm"
          onClick={() => {
            window.location.href = LOGOUT_URL
          }}
        >
          Déconnexion
        </Button>
      </div>
    </header>
  )
}
