// forge-app/front/components/layout/sidebar.tsx
"use client"

import Link from "next/link"
import { usePathname } from "next/navigation"
import {
  Boxes,
  ChartLine,
  ClipboardList,
  Coins,
  FileText,
  Gauge,
  Globe,
  Hammer,
  Package,
  ScrollText,
  Settings,
  Shield,
  User,
  type LucideIcon,
} from "lucide-react"
import { cn } from "@/lib/utils"
import { useCurrentBusiness } from "@/lib/current-business"
import { canAdminBusiness, canStaffView } from "@/lib/roles"
import { useSession } from "@/lib/session"

type NavItem = {
  href: string
  label: string
  icon: LucideIcon
}

const primaryNavItems: NavItem[] = [
  { href: "/dashboard", label: "Dashboard", icon: Gauge },
  { href: "/facturation", label: "Facturation", icon: FileText },
  { href: "/commandes", label: "Commandes", icon: ClipboardList },
  { href: "/stock", label: "Stock", icon: Hammer },
  { href: "/rachat", label: "Créances", icon: Coins },
  { href: "/main-courante", label: "Main courante", icon: ScrollText },
  { href: "/statistiques", label: "Statistiques", icon: ChartLine },
  { href: "/catalogue", label: "Catalogue", icon: Package },
]

function isCurrentPath(pathname: string, href: string) {
  return pathname === href || pathname.startsWith(`${href}/`)
}

function NavLink({ item, pathname }: { item: NavItem; pathname: string }) {
  const Icon = item.icon
  const active = isCurrentPath(pathname, item.href)

  return (
    <Link
      href={item.href}
      aria-current={active ? "page" : undefined}
      className={cn(
        "flex h-10 items-center gap-3 rounded-md px-3 text-sm font-medium transition",
        active
          ? "bg-sidebar-accent text-sidebar-accent-foreground shadow-sm"
          : "text-sidebar-foreground/75 hover:bg-sidebar-accent/70 hover:text-sidebar-accent-foreground",
      )}
    >
      <Icon data-icon="inline-start" />
      <span className="truncate">{item.label}</span>
    </Link>
  )
}

export function Sidebar() {
  const pathname = usePathname()
  const me = useSession()
  const { currentId } = useCurrentBusiness()

  const isSystem = me.user.globalRole === "SYSTEM"
  const canConfig = currentId ? canAdminBusiness(me, currentId) : false

  // Configuration = menu du business → dans le menu principal (pas dans les options du bas).
  const primary: NavItem[] = [
    ...primaryNavItems,
    ...(canConfig ? [{ href: "/configuration", label: "Configuration", icon: Settings }] : []),
  ]

  const secondaryNavItems: NavItem[] = [
    ...(canStaffView(me) ? [{ href: "/staff", label: "Vue staff", icon: Globe }] : []),
    ...(isSystem ? [{ href: "/systeme", label: "Système", icon: Boxes }] : []),
    ...(isSystem ? [{ href: "/admin", label: "Administration", icon: Shield }] : []),
    { href: "/profil", label: "Profil", icon: User },
  ]

  return (
    <aside className="sticky top-0 hidden h-screen w-72 shrink-0 overflow-y-auto border-r bg-sidebar/80 px-4 py-5 lg:block">
      <div className="flex min-h-full flex-col">
        <Link href="/dashboard" className="flex items-center gap-3 rounded-md px-2 py-1.5">
          <div className="flex size-10 items-center justify-center rounded-md bg-primary text-primary-foreground">
            <Hammer data-icon="inline-start" />
          </div>
          <div className="min-w-0">
            <p className="truncate text-lg font-semibold leading-none">Forge RP</p>
            <p className="truncate text-xs text-muted-foreground">Gestion atelier</p>
          </div>
        </Link>

        <nav className="mt-8 flex flex-col gap-1">
          {primary.map((item) => (
            <NavLink key={item.href} item={item} pathname={pathname} />
          ))}
        </nav>

        <nav className="mt-auto flex flex-col gap-1 border-t pt-4">
          {secondaryNavItems.map((item) => (
            <NavLink key={item.href} item={item} pathname={pathname} />
          ))}
        </nav>
      </div>
    </aside>
  )
}

// forge-app/front/src/components/Sidebar.svelte
<script>
  import { router } from 'svelte-spa-router'
  import {
    Gauge, FileText, ClipboardList, Hammer, Coins, ScrollText, ChartLine,
    Package, Settings, Globe, Boxes, User,
  } from '@lucide/svelte'
  import { me, currentBusinessId, currentBusiness } from '../lib/session.js'
  import { canAdminBusiness, canStaffView } from '../lib/roles.js'

  let { open = false, onClose = () => {} } = $props()

  const primaryBase = [
    { href: '/dashboard', label: 'Dashboard', icon: Gauge },
    { href: '/facturation', label: 'Facturation', icon: FileText },
    { href: '/commandes', label: 'Commandes', icon: ClipboardList },
    { href: '/stock', label: 'Stock', icon: Hammer },
    { href: '/rachat', label: 'Créances', icon: Coins },
    { href: '/main-courante', label: 'Main courante', icon: ScrollText },
    { href: '/statistiques', label: 'Statistiques', icon: ChartLine },
    { href: '/catalogue', label: 'Catalogue', icon: Package },
  ]

  let isSystem = $derived($me.user.globalRole === 'SYSTEM')
  let canConfig = $derived($currentBusinessId ? canAdminBusiness($me, $currentBusinessId) : false)
  // Créances réservées aux Compagnies (les forges n'ont pas de farmeurs à rembourser).
  let isCompagnie = $derived($currentBusiness?.type === 'COMPAGNIE')

  let primary = $derived([
    ...primaryBase.filter((it) => it.href !== '/rachat' || isCompagnie),
    ...(canConfig ? [{ href: '/configuration', label: 'Configuration', icon: Settings }] : []),
  ])
  let secondary = $derived([
    ...(canStaffView($me) ? [{ href: '/staff', label: 'Vue staff', icon: Globe }] : []),
    ...(isSystem ? [{ href: '/systeme', label: 'Système', icon: Boxes }] : []),
    { href: '/profil', label: 'Profil', icon: User },
  ])

  function isActive(href) {
    return router.location === href || router.location.startsWith(href + '/')
  }
</script>

{#snippet navContent()}
  <a href="#/dashboard" onclick={onClose} class="flex items-center gap-3 rounded-md px-2 py-1.5">
    <div class="flex size-10 items-center justify-center rounded-md bg-primary text-primary-foreground">
      <Hammer size={20} />
    </div>
    <div class="min-w-0">
      <p class="truncate text-lg font-semibold leading-none">Forge</p>
      <p class="truncate text-xs text-muted-foreground">Gestion atelier</p>
    </div>
  </a>

  <nav class="mt-8 flex flex-col gap-1">
    {#each primary as item (item.href)}
      {@const Icon = item.icon}
      <a
        href={'#' + item.href}
        onclick={onClose}
        aria-current={isActive(item.href) ? 'page' : undefined}
        class="flex h-10 items-center gap-3 rounded-md px-3 text-sm font-medium transition {isActive(item.href)
          ? 'bg-sidebar-accent text-sidebar-accent-foreground shadow-sm'
          : 'text-sidebar-foreground/75 hover:bg-sidebar-accent/70 hover:text-sidebar-accent-foreground'}"
      >
        <Icon size={18} />
        <span class="truncate">{item.label}</span>
      </a>
    {/each}
  </nav>

  <nav class="mt-auto flex flex-col gap-1 border-t pt-4">
    {#each secondary as item (item.href)}
      {@const Icon = item.icon}
      <a
        href={'#' + item.href}
        onclick={onClose}
        aria-current={isActive(item.href) ? 'page' : undefined}
        class="flex h-10 items-center gap-3 rounded-md px-3 text-sm font-medium transition {isActive(item.href)
          ? 'bg-sidebar-accent text-sidebar-accent-foreground shadow-sm'
          : 'text-sidebar-foreground/75 hover:bg-sidebar-accent/70 hover:text-sidebar-accent-foreground'}"
      >
        <Icon size={18} />
        <span class="truncate">{item.label}</span>
      </a>
    {/each}
  </nav>
{/snippet}

<!-- Desktop : barre latérale fixe -->
<aside class="sticky top-0 hidden h-screen w-72 shrink-0 overflow-y-auto border-r bg-sidebar/80 px-4 py-5 lg:block">
  <div class="flex min-h-full flex-col">{@render navContent()}</div>
</aside>

<!-- Mobile/tablette : tiroir coulissant -->
{#if open}
  <div class="fixed inset-0 z-50 lg:hidden">
    <div class="absolute inset-0 bg-black/60" onclick={onClose} role="presentation"></div>
    <aside class="absolute left-0 top-0 flex h-full w-72 flex-col overflow-y-auto border-r bg-sidebar px-4 py-5 shadow-2xl">
      {@render navContent()}
    </aside>
  </div>
{/if}
