// forge-app/front/src/pages/Admin.svelte
<script>
  import { onMount } from 'svelte'
  import { api, ApiError } from '../lib/api.js'
  import { notifySuccess, notifyError } from '../lib/notifications.js'
  import PageHeader from '../components/PageHeader.svelte'
  import Card from '../components/ui/Card.svelte'
  import CardHeader from '../components/ui/CardHeader.svelte'
  import CardTitle from '../components/ui/CardTitle.svelte'
  import CardContent from '../components/ui/CardContent.svelte'
  import Input from '../components/ui/Input.svelte'
  import Button from '../components/ui/Button.svelte'
  import Badge from '../components/ui/Badge.svelte'
  import SelectField from '../components/ui/SelectField.svelte'

  let businesses = $state([])
  let nom = $state('')
  let type = $state('FORGE')

  function fail(e) {
    notifyError(e instanceof ApiError ? e.message : 'Erreur inattendue')
  }

  async function load() {
    try {
      businesses = await api('/api/businesses')
    } catch (e) {
      fail(e)
    }
  }

  onMount(load)

  async function createBusiness() {
    if (!nom.trim()) return
    try {
      await api('/api/businesses', { method: 'POST', body: JSON.stringify({ nom: nom.trim(), type }) })
      nom = ''
      notifySuccess('Business créé')
      load()
    } catch (e) {
      fail(e)
    }
  }
</script>

<PageHeader title="Administration" description="Création et liste des business." />

<Card>
  <CardHeader><CardTitle>Créer un business</CardTitle></CardHeader>
  <CardContent class="flex flex-wrap items-center gap-2">
    <Input class="max-w-xs" placeholder="Nom du business" bind:value={nom} />
    <SelectField
      value={type}
      onChange={(v) => (type = v)}
      options={[
        { value: 'FORGE', label: 'FORGE' },
        { value: 'COMPAGNIE', label: 'COMPAGNIE' },
      ]}
    />
    <Button onclick={createBusiness}>Créer</Button>
  </CardContent>
</Card>

<div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
  {#each businesses as b (b.id)}
    <Card>
      <CardHeader>
        <div class="flex items-center justify-between">
          <CardTitle>{b.nom}</CardTitle>
          <Badge variant="outline">{b.type}</Badge>
        </div>
      </CardHeader>
    </Card>
  {/each}
  {#if businesses.length === 0}
    <p class="text-sm text-muted-foreground">Aucun business.</p>
  {/if}
</div>

<p class="text-sm text-muted-foreground">
  Membres, taxe et logo : sélectionne le business (en haut) puis ouvre <strong>Configuration</strong>.
</p>

// forge-app/front/app/admin/page.tsx
"use client"

import { useCallback, useEffect, useState } from "react"
import { toast } from "sonner"
import { AppShell } from "@/components/layout/app-shell"
import { PageHeader } from "@/components/layout/page-header"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { SelectField } from "@/components/ui/select-field"
import { api, ApiError } from "@/lib/api"
import type { BusinessType } from "@/lib/roles"

type BusinessDto = { id: string; nom: string; type: BusinessType; createdAt: string }

function fail(err: unknown) {
  toast.error(err instanceof ApiError ? err.message : "Erreur inattendue")
}

function AdminContent() {
  const [businesses, setBusinesses] = useState<BusinessDto[]>([])
  const [nom, setNom] = useState("")
  const [type, setType] = useState<BusinessType>("FORGE")

  const load = useCallback(() => {
    api<BusinessDto[]>("/api/businesses").then(setBusinesses).catch(fail)
  }, [])

  useEffect(() => load(), [load])

  async function createBusiness() {
    if (!nom.trim()) return
    try {
      await api<BusinessDto>("/api/businesses", {
        method: "POST",
        body: JSON.stringify({ nom: nom.trim(), type }),
      })
      setNom("")
      toast.success("Business créé")
      load()
    } catch (err) {
      fail(err)
    }
  }

  return (
    <>
      <PageHeader title="Administration" description="Création et liste des business." />

      <Card>
        <CardHeader>
          <CardTitle>Créer un business</CardTitle>
        </CardHeader>
        <CardContent className="flex flex-wrap items-center gap-2">
          <Input
            className="max-w-xs"
            placeholder="Nom du business"
            value={nom}
            onChange={(e) => setNom(e.target.value)}
          />
          <SelectField
            value={type}
            onChange={(v) => setType(v as BusinessType)}
            options={[
              { value: "FORGE", label: "FORGE" },
              { value: "COMPAGNIE", label: "COMPAGNIE" },
            ]}
          />
          <Button onClick={createBusiness}>Créer</Button>
        </CardContent>
      </Card>

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
        {businesses.map((b) => (
          <Card key={b.id}>
            <CardHeader>
              <div className="flex items-center justify-between">
                <CardTitle>{b.nom}</CardTitle>
                <Badge variant="outline">{b.type}</Badge>
              </div>
            </CardHeader>
          </Card>
        ))}
        {businesses.length === 0 ? <p className="text-sm text-muted-foreground">Aucun business.</p> : null}
      </div>

      <p className="text-sm text-muted-foreground">
        Membres, taxe et logo : sélectionne le business (en haut) puis ouvre <strong>Configuration</strong>.
      </p>
    </>
  )
}

export default function AdminPage() {
  return (
    <AppShell>
      <AdminContent />
    </AppShell>
  )
}
